In [7]:
pip install pydataset

Note: you may need to restart the kernel to use updated packages.


In [54]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
from pydataset import data #search
from statsmodels.formula.api import ols #search
from sklearn import linear_model as lm
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score, accuracy_score

In [55]:
mtcars= data('mtcars')
mtcars.head()

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
Mazda RX4          21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
Mazda RX4 Wag      21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
Datsun 710         22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
Hornet 4 Drive     21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

                   carb  
Mazda RX4             4  
Mazda RX4 Wag         4  
Datsun 710            1  
Hornet 4 Drive        1  
Hornet Sportabout     2

In [56]:
df=mtcars

In [57]:
df.head()o

SyntaxError: invalid syntax (3463374185.py, line 1)

In [58]:
df1= df[['mpg','wt','hp']]
df1.head()

mpg     wt   hp
Mazda RX4          21.0  2.620  110
Mazda RX4 Wag      21.0  2.875  110
Datsun 710         22.8  2.320   93
Hornet 4 Drive     21.4  3.215  110
Hornet Sportabout  18.7  3.440  175

In [59]:
x= df1[['wt','hp']].values
x

array([[  2.62 , 110.   ],
       [  2.875, 110.   ],
       [  2.32 ,  93.   ],
       [  3.215, 110.   ],
       [  3.44 , 175.   ],
       [  3.46 , 105.   ],
       [  3.57 , 245.   ],
       [  3.19 ,  62.   ],
       [  3.15 ,  95.   ],
       [  3.44 , 123.   ],
       [  3.44 , 123.   ],
       [  4.07 , 180.   ],
       [  3.73 , 180.   ],
       [  3.78 , 180.   ],
       [  5.25 , 205.   ],
       [  5.424, 215.   ],
       [  5.345, 230.   ],
       [  2.2  ,  66.   ],
       [  1.615,  52.   ],
       [  1.835,  65.   ],
       [  2.465,  97.   ],
       [  3.52 , 150.   ],
       [  3.435, 150.   ],
       [  3.84 , 245.   ],
       [  3.845, 175.   ],
       [  1.935,  66.   ],
       [  2.14 ,  91.   ],
       [  1.513, 113.   ],
       [  3.17 , 264.   ],
       [  2.77 , 175.   ],
       [  3.57 , 335.   ],
       [  2.78 , 109.   ]])

In [60]:
y=df1[['mpg']]
y.values

array([[21. ],
       [21. ],
       [22.8],
       [21.4],
       [18.7],
       [18.1],
       [14.3],
       [24.4],
       [22.8],
       [19.2],
       [17.8],
       [16.4],
       [17.3],
       [15.2],
       [10.4],
       [10.4],
       [14.7],
       [32.4],
       [30.4],
       [33.9],
       [21.5],
       [15.5],
       [15.2],
       [13.3],
       [19.2],
       [27.3],
       [26. ],
       [30.4],
       [15.8],
       [19.7],
       [15. ],
       [21.4]])

In [61]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=12)

In [62]:
x_train.shape

(25, 2)

In [63]:
a=lm.LinearRegression()

In [64]:
a

LinearRegression()

In [65]:
a.fit(x_train,y_train)

LinearRegression()

In [66]:
a.intercept_

array([37.09123098])

In [67]:
a.coef_

array([[-4.00965575, -0.02872778]])

In [68]:
a_pred=a.predict(x_test)

In [69]:
a_pred

array([[22.51930657],
       [16.64674254],
       [29.12179221],
       [10.15134271],
       [22.40341453],
       [14.65584599],
       [18.27065312]])

In [78]:
y_test.shape

(7, 1)

In [70]:
accuracy_score(y_test,a_pred)

ValueError: continuous is not supported

In [71]:
mean_squared_error(y_test,a_pred)

2.249143780377783

In [72]:
r2_score(y_test,a_pred)

0.9410191672436707

In [74]:
model1=ols("mpg ~ wt+hp",data=df1).fit()


In [75]:
print(model1.summary())

                            OLS Regression Results                            
Dep. Variable:                    mpg   R-squared:                       0.827
Model:                            OLS   Adj. R-squared:                  0.815
Method:                 Least Squares   F-statistic:                     69.21
Date:                Sun, 19 Feb 2023   Prob (F-statistic):           9.11e-12
Time:                        19:37:26   Log-Likelihood:                -74.326
No. Observations:                  32   AIC:                             154.7
Df Residuals:                      29   BIC:                             159.0
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     37.2273      1.599     23.285      0.0

In [76]:
pred=model1.predict()

In [77]:
pred

array([23.5723294 , 22.58348256, 25.27581872, 21.26502011, 18.32726664,
       20.47381631, 15.59904236, 22.88706734, 21.99367331, 19.97945988,
       19.97945988, 15.72536854, 17.04383099, 16.84993945, 10.35520459,
        9.36273257,  9.19248699, 26.59902798, 29.31238022, 28.04620915,
       24.58644148, 18.81136386, 19.14097947, 14.55202805, 16.75674519,
       27.62665313, 26.03737415, 27.76976919, 16.54648866, 20.92541324,
       12.73947713, 22.98364943])