In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import neighbors, datasets, preprocessing
from x_sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [3]:
iris=datasets.load_iris()

In [4]:
x,y = iris.data[:,:2], iris.target

In [19]:
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size=0.2, random_state=1)

In [20]:
print(x_train)

[[6.1 3. ]
 [7.7 3. ]
 [5.6 2.5]
 [6.4 2.8]
 [5.8 2.8]
 [5.3 3.7]
 [5.5 2.3]
 [5.2 3.4]
 [6.5 2.8]
 [6.7 2.5]
 [6.8 3. ]
 [5.1 3.5]
 [6.  2.2]
 [6.3 2.9]
 [6.6 2.9]
 [7.7 2.6]
 [5.7 3.8]
 [5.  3.6]
 [4.8 3. ]
 [5.2 2.7]
 [5.1 3.4]
 [5.5 3.5]
 [7.7 3.8]
 [6.9 3.1]
 [7.3 2.9]
 [6.4 2.8]
 [6.2 2.8]
 [6.  3.4]
 [7.7 2.8]
 [5.7 3. ]
 [4.8 3.4]
 [5.7 2.5]
 [6.3 2.7]
 [4.8 3. ]
 [4.7 3.2]
 [6.5 3. ]
 [4.6 3.4]
 [6.1 3. ]
 [6.5 3.2]
 [6.7 3.1]
 [5.7 2.8]
 [6.7 3.3]
 [6.  3. ]
 [5.1 3.8]
 [6.  2.2]
 [6.4 2.9]
 [6.5 3. ]
 [5.  2.3]
 [6.3 3.3]
 [5.5 2.5]
 [5.4 3.7]
 [4.9 3.1]
 [5.2 4.1]
 [6.7 3.3]
 [4.4 3. ]
 [6.  2.7]
 [6.4 2.7]
 [5.9 3. ]
 [5.2 3.5]
 [5.1 3.3]
 [5.8 2.7]
 [4.9 3.1]
 [7.4 2.8]
 [6.2 2.9]
 [7.6 3. ]
 [6.7 3. ]
 [6.3 2.3]
 [6.2 3.4]
 [7.2 3.6]
 [5.6 2.9]
 [5.7 4.4]
 [5.8 2.7]
 [4.5 2.3]
 [5.5 2.4]
 [6.9 3.1]
 [5.  3.4]
 [6.8 2.8]
 [5.  3.5]
 [4.8 3.4]
 [6.3 3.4]
 [5.6 2.8]
 [6.8 3.2]
 [5.  3.3]
 [5.1 3.7]
 [5.9 3.2]
 [4.6 3.1]
 [5.8 2.7]
 [4.8 3.1]
 [6.5 3. ]
 [4.9 2.5]
 [4.6 3.2]

In [21]:
print(x_test)

[[5.8 4. ]
 [5.1 2.5]
 [6.6 3. ]
 [5.4 3.9]
 [7.9 3.8]
 [6.3 3.3]
 [6.9 3.1]
 [5.1 3.8]
 [4.7 3.2]
 [6.9 3.2]
 [5.6 2.7]
 [5.4 3.9]
 [7.1 3. ]
 [6.4 3.2]
 [6.  2.9]
 [4.4 3.2]
 [5.8 2.6]
 [5.6 3. ]
 [5.4 3.4]
 [5.  3.2]
 [5.5 2.6]
 [5.4 3. ]
 [6.7 3. ]
 [5.  3.5]
 [7.2 3.2]
 [5.7 2.8]
 [5.5 4.2]
 [5.1 3.8]
 [6.1 2.8]
 [6.3 2.5]]


In [22]:
scaler= preprocessing.StandardScaler().fit(x_train)
print(scaler)

StandardScaler()


In [23]:
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)

In [24]:
print(x_train)

[[ 0.31553662 -0.04578885]
 [ 2.2449325  -0.04578885]
 [-0.2873996  -1.24028061]
 [ 0.67729835 -0.52358555]
 [-0.04622511 -0.52358555]
 [-0.64916132  1.62649961]
 [-0.40798684 -1.71807731]
 [-0.76974857  0.90980456]
 [ 0.79788559 -0.52358555]
 [ 1.03906007 -1.24028061]
 [ 1.15964732 -0.04578885]
 [-0.89033581  1.14870291]
 [ 0.19494938 -1.95697567]
 [ 0.5567111  -0.2846872 ]
 [ 0.91847283 -0.2846872 ]
 [ 2.2449325  -1.00138226]
 [-0.16681235  1.86539796]
 [-1.01092305  1.38760126]
 [-1.25209754 -0.04578885]
 [-0.76974857 -0.76248391]
 [-0.89033581  0.90980456]
 [-0.40798684  1.14870291]
 [ 2.2449325   1.86539796]
 [ 1.28023456  0.1931095 ]
 [ 1.76258353 -0.2846872 ]
 [ 0.67729835 -0.52358555]
 [ 0.43612386 -0.52358555]
 [ 0.19494938  0.90980456]
 [ 2.2449325  -0.52358555]
 [-0.16681235 -0.04578885]
 [-1.25209754  0.90980456]
 [-0.16681235 -1.24028061]
 [ 0.5567111  -0.76248391]
 [-1.25209754 -0.04578885]
 [-1.37268478  0.43200785]
 [ 0.79788559 -0.04578885]
 [-1.49327202  0.90980456]
 

In [25]:
print(x_test)

[[-0.04622511  2.34319467]
 [-0.89033581 -1.24028061]
 [ 0.91847283 -0.04578885]
 [-0.52857408  2.10429632]
 [ 2.48610699  1.86539796]
 [ 0.5567111   0.6709062 ]
 [ 1.28023456  0.1931095 ]
 [-0.89033581  1.86539796]
 [-1.37268478  0.43200785]
 [ 1.28023456  0.43200785]
 [-0.2873996  -0.76248391]
 [-0.52857408  2.10429632]
 [ 1.52140905 -0.04578885]
 [ 0.67729835  0.43200785]
 [ 0.19494938 -0.2846872 ]
 [-1.73444651  0.43200785]
 [-0.04622511 -1.00138226]
 [-0.2873996  -0.04578885]
 [-0.52857408  0.90980456]
 [-1.01092305  0.43200785]
 [-0.40798684 -1.00138226]
 [-0.52857408 -0.04578885]
 [ 1.03906007 -0.04578885]
 [-1.01092305  1.14870291]
 [ 1.64199629  0.43200785]
 [-0.16681235 -0.52358555]
 [-0.40798684  2.82099137]
 [-0.89033581  1.86539796]
 [ 0.31553662 -0.52358555]
 [ 0.5567111  -1.24028061]]


In [26]:
knn=neighbors.KNeighborsClassifier(n_neighbors=4)

In [27]:
knn.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=4)

In [30]:
y_pred=knn.predict(x_test)

C:\Users\nagan\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [39]:
accuracy_score(y_test,y_pred, normalize= True)

0.7666666666666667

In [38]:
#check missing values in a dataset 
#df.isnull().sum() for local dataset
#df.isnull().sum().sum()

In [41]:
from sklearn.metrics import classification_report

In [42]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       0.71      0.77      0.74        13
           2       0.40      0.33      0.36         6

    accuracy                           0.77        30
   macro avg       0.70      0.70      0.70        30
weighted avg       0.76      0.77      0.76        30



In [43]:
from sklearn.metrics import confusion_matrix

In [44]:
print(confusion_matrix(y_test, y_pred))

[[11  0  0]
 [ 0 10  3]
 [ 0  4  2]]
